########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  ######## Stellar ########
  - https://api.github.com/repos/Kemeow0815/blog-timeline/issues?per_page=20
